
spring:
  profiles:
    active: dev # local # prod

  mvc:
    path-match:
      matching-strategy: ant_path_matcher # Swagger path
  jpa:
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        time_zone: Asia/Seoul

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
